import streamlit as st
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
from st_files_connection import FilesConnection
from pystac_client import Client
from odc.stac import load
import hmac

def check_password():
    def login_form():
        with st.form("credentials"):
            st.text_input("Username" ,key ="username")
            st.text_input("Password", type="password",key="password")
            st.form_submit_button("Login", on_click=password_entered)
    def password_entered():
        if st.session_state["username"] in st.secrets["passwords"] and hmac.compare_digest(
            st.session_state["password"],
            st.secrets.passwords[st.session_state["username"]]
        ):
            st.session_state["password_correct"] = True
            del st.session_state["password"]
            del st.session_state["username"]
        else:
            st.session_state["password_correct"] = False
    if st.session_state.get("password_correct", False):  ### the user is logged in.
        return True
    login_form()    #### If the user is not logged in, displays the login form.
    if "password_correct" in st.session_state:
        st.error("😕 User not known or password incorrect")
    return False
if not check_password():
    st.stop()